export interface IStock {
    stock_name: string;
    stock_symbol:string;
    base_price:number;
  }
  // Generated by https://quicktype.io

export interface ITxn {
  stock_name:        string;
  stock_symbol:      string;
  transaction_price: number;
  timestamp:         string;
  status:            string;
}
